### ISSUE TITLE
Local command-line not working when symfonyflex-bridge is enabled

### ISSUE THREAD

**Issue by cirdan** [platformsh/symfonyflex-bridge#3]
**Context:**
- Symfony 4 application
- PHP 7.2
- MacOSX (local development)
- Running console commands involving the connection
- (Application runs OK on platform.sh)

**Symptom:**
Try to run `php bin/console doctrine:database:drop`
The symfony console complains about `An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)` on my local environment, after having updated composer with symfonyflex-bridge

If I set the environment variable in the line executing the console, it's OK :
`DATABASE_URL=mysql://MYUSER:MYPASSWORD@127.0.0.1:3306/MYDATABASE php bin/console doctrine:database:drop`

If I bypass the symfonyflex-bridge (modifying its code), it's OK.

As I understand, the function `mapPlatformShEnvironment` should check that we are on platform.sh before doing anything ? (maybe by looking at `$_ENV['PLATFORM_RELATIONSHIPS']` ?)

**Comment by Crell** [comment]
Addressed in #5

**Comment by cirdan** [comment]
Sorry, I hadn't the time to give a feedback on this. 
Perfect for me, thank you !
