### ISSUE TITLE
rabbitmq support for messenger?

### ISSUE THREAD

**Issue by patie** [platformsh/symfonyflex-bridge#34]
Hi, what about support of symfony messenger? MESSENGER_TRANSPORT_DSN variable

**Comment by Crell** [comment]
There's some WIP on that front here: #28 

Right now there's some design questions to sort out, plus I'd like to get the Elasticsearch support (#25) landed first to avoid commit collisions.

(Input/help on either of those points is most welcome.  Especially testing to make sure it actually works as intended on a real application.)

**Comment by Crell** [comment]
This has since been added.
