### ISSUE TITLE
Missing population of `PLATFORM_VARIABLES`

### ISSUE THREAD

**Issue by olivermack** [platformsh/symfonyflex-bridge#6]
Hey,

it seems as if this package is missing the mapping of the `PLATFORM_VARIABLES` env variable which contains _the other_ variables one can define in the platform.sh UI.

Is this intended or just missing? I'm happy to contribute that part if it's missing.

Cheers

**Comment by Crell** [comment]
Variables that are prefixed with `env:` are converted to environment variables automatically by the backend system.  No user-space code is necessary for that.

Mapping non-env-prefixed variables to top level env vars would be unexpected and not the contract of the API.

Thanks for checking, though!

**Comment by olivermack** [comment]
Oh jeez... Didn't know that.
Awesome, thanks for the fast feedback!

Just checked it and it works indeed 👍
