### ISSUE TITLE
DATABASE_URL is not available using getenv()

### ISSUE THREAD

**Issue by nmeirik** [platformsh/symfonyflex-bridge#9]
It would be great if the bridge would, in addition to setting variables like `DATABASE_URL` as a `$_SERVER` parameter, also make use of `putenv()` to ensure that the variables will be accessible using `getenv()`

**Comment by Crell** [comment]
The Env component, as far as I understand, checks both/all locations.  If you're using the Env component (which you have to in order to get the .env file to work) then it should already be covered, no?

**Comment by Plopix** [comment]
the Env component is not supposed to be used in production mode, is it?

**Comment by nmeirik** [comment]
I can confirm that getting the `DATABASE_URL` using `getenv()` does indeed not work in production, and I had to fall back to using the `$_SERVER` variable.

The [documentation](https://symfony.com/doc/current/components/dotenv.html) says:

> Symfony Dotenv should only be used in development/testing/staging environments. For production environments, use "real" environment variables.

**Comment by Crell** [comment]
That seems kinda silly to me, frankly, but oh well.  Here's a PR to fix it: #10.

Closing this thread in favor of that one.  Tests/+1s welcome before merging.
